### ISSUE TITLE
enregistrement du fichier uploadé

### ISSUE THREAD

**Issue by byache** [byache/wimsActivityViewer#1]
https://github.com/byache/wimsActivityViewer/blob/5781dfe317a94331040c7a8f781beeab7e95acab/wav.py#L10

c'est pas terrible : 
- à cause de zipfile, je suis obligé d'enregistré d'enregistrer le fichier dans le système de fichiers du serveur
- je suis "obligé" d'enregistrer dans le répertoire de travail car sinon le path ici doit être non relatif (sinon : bug)

solutions que je préfèrerais : 
- ne pas enregistrer le fichier zip sur le serveur (mais zipfile ne convient plus, il faudrait autre chose...)
- l'enregistrer dans un autre dossier (mais il faudra voir le chemin absolu lors de la mise en prod)
- l'effacer à la fin du script (moins pire des solutions)

**Comment by cspaier** [comment]
je ne sais pas où tu as lu que Zipfile ne pouvait pas travailler en mémoire.
Tu as des solutions [ici](https://stackoverflow.com/questions/5710867/downloading-and-unzipping-a-zip-file-without-writing-to-disk/42119017) ou [la](https://stackoverflow.com/questions/10908877/extracting-a-zipfile-to-memory).

**Comment by byache** [comment]
Ha oui, merci ! Je n'avais pas pensé à ça...
